### PR TITLE
Revamp Resize.php

### PR DESCRIPTION
**Pull request by ghost**
This is a new version of Simple image. From my Apache2 logs, it has less errors than the old one. 

I still believe it needs work doing to it which I shall do.

### CODE REVIEW

**Comment by rshendershot** [comment]
Hi William.  There are a few problems with this request.  The original author has not been around for a long while now but did give me access.  I've kept ear9mrn-master updated with MythTV version changes, but I have my own branch.  I don't know what he intended for his Dev branch but anything you patch should be against his master, not dev.

As for me, I no longer use the mythweb dependancies and replaced resizeimage with a call to the MythTV Backend services.  I never saw httpd errors originating from this as far as I remember.  Guidance on what to look for and how to reproduce the problem would help in verifying the pull request.

**Comment by ghost** [comment]
Hi rshendershot, 

How did you make this call to the MythTV Backend?

**Comment by rshendershot** [comment]
You can see the API at your mythbackendserverip:6544.  You should see a Status of your mythtv backend.  There's an API menu on the left.  Calling content/GetPreviewImage causes the mythtv backend to generate an image for that recording by its keys (ChanId, StartTime).  This one is a GET but there are POST services.

**Comment by rshendershot** [comment]
Resize is only used for Videos and being called by image.php.  That has a dependency on a symlink but never passes the server url.  Parsing that out of load(filename) seems redundant and would cause problems if the expected resource did not reside on the local machine (as in my Weather item).

**Pull request closed without merging**
