### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by zane131**
Resolved many bug fixes.
Fixed issue #8 and #9.
Removed the need for $RokuDisplayType in settings.php.
Added the support for true directory structures.
Added the support to show episodes by TV Series => Season => Episode directory structure.
Improved the ability to sort by title, date, and genre.
Added TV Ratings for recordings.

### CODE REVIEW

**Comment by cpinkham** [comment]
One thing that may help with this in the future.  MythTV has a schema change that will be coming along at some point which will allow tracking multiple files per recording, so you'll be able to store a transcoded .mp4 file alongside the original .mpg if you want.  It will need a lot of updates to make that info available and usable everywhere, but since you're accessing the DB directly, you'll be able to do this once the changes are in place.  No ETA on when yet, the schema is designed but not a lot of work has been done around writing code to use it yet.

**Comment by rshendershot** [comment]
interesting!  thanks for the heads up.   is the schema docs online yet?
If not, is Recorded being broken out into associated tables?

**Comment by cpinkham** [comment]
http://code.mythtv.org/trac/wiki/TaskRecordedFile has the proposed schema
changes with inline comments.  There's probably still a little tweaking
going on, I created the initial draft and Michael T Dean has been
mainly driving it since then as well as input from a few others over time.
Another change which may come along at the same time is adding a 
'recording ID' to use to index a recording instead of using chanid and
starttime to join everything together.  That isn't reflected in the
above schema.

## 

Chris

**Comment by rshendershot** [comment]
nice. most makes sense to me.

My hope for mythrokuplayer is to present a list of iPlayable.  this seems
to be going in that direction and would certainly make our part of it
easier if we wait.  Can you box ETA a little tighter?  Say before 0.27?

**Comment by cpinkham** [comment]
- On Fri Oct 12, 2012 at 07:51:35AM -0700, rshendershot wrote:
  > My hope for mythrokuplayer is to present a list of iPlayable.  this seems
  > to be going in that direction and would certainly make our part of it
  > easier if we wait.  Can you box ETA a little tighter?  Say before 0.27?

I can't commit to a time since I'm not working on it, but I
believe that Michael says he wants to get the schema change in before
0.27, even if we don't have all the code converted over to use it's
new features.

## 

Chris

**Comment by zane131** [comment]
I think I have resolved most of the issues that had been found in this branch. Please review and test so that we can finally get it merged into master (sorry this took so long).

**Comment by rshendershot** [comment]
I was working on a virtual machine setup of MythTV 0.25 yesterday and ran
into a snag.  I have upgraded all my recorders to 0.26.  I'll have another
go at it ASAP.

**Comment by rshendershot** [comment]
this PR would be broken by recent fixes I made to allow use of the original MRP channel.

**Pull request closed without merging**
